### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by afgks** [die/calibre-rpc#9]
Hello, thanks for making this plugin!

I would really appreciate it if you can make these changes:
1. Status should go back to "Browsing Library" after the e-book viewer or editor is closed.
2. Status should change to "Editing metadata" when the user opens the edit metadata window.

**Comment by die** [comment]
Hey, thank you for the suggestions.

I believe the e-book viewer (and probably the editor as well) is detached from Calibre so there's no way of knowing when it closes without doing stuff that a plugin should probably not be able to do. I'm not too fond of that approach, but I can research into this again and see what I can do. Should be able to add an editing metadata status without much issue.

**Comment by die** [comment]
I'll be closing this issue. For now, a submenu button has been added to set the status back to browsing as a temporary fix. If there are any updates for detecting when the ebook viewer/editor closes, this issue can be re-opened. Thanks again for your input.
